# Generated by Django 4.0.4 on 2022-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='package',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
